ready for deploy

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -3,3 +3,45 @@
 # build hook has been run but before the application has been started back
 # up again.  This script gets executed directly, so it could be python, php,
 # ruby, etc.
+
+if [ ! -d $OPENSHIFT_DATA_DIR/wordpress ]; then
+	mkdir $OPENSHIFT_DATA_DIR/wordpress
+	(cd $OPENSHIFT_DATA_DIR/wordpress;wget http://wordpress.org/latest.tar.gz;tar xfz $OPENSHIFT_DATA_DIR/wordpress/latest.tar.gz;mv $OPENSHIFT_DATA_DIR/wordpress/wordpress/* $OPENSHIFT_DATA_DIR/wordpress/;rmdir $OPENSHIFT_DATA_DIR/wordpress/wordpress/;rm -f $OPENSHIFT_DATA_DIR/wordpress/latest.tar.gz)
+fi
+
+cp -f $OPENSHIFT_REPO_DIR/.openshift/wp-config.php $OPENSHIFT_DATA_DIR/wordpress/wp-config.php
+ln -sf $OPENSHIFT_DATA_DIR/wordpress/* $OPENSHIFT_REPO_DIR/php/
+
+set -e
+
+if [ -z $OPENSHIFT_MYSQL_DB_HOST ]
+then
+	echo 1>&2
+	echo "Could not find mysql database.  Please run:" 1>&2
+	echo "rhc app cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
+	echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+	echo 1>&2
+	exit 5
+fi
+
+# check for database.
+if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -e "show tables;" $OPENSHIFT_APP_NAME > /dev/null
+then
+	echo 1>&2
+	echo "Could not find mysql database. " 1>&2
+	echo "Creating database for application named: $OPENSHIFT_APP_NAME." 1 >&2
+	/usr/bin/mysqladmin -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" create "$OPENSHIFT_APP_NAME"
+fi
+
+# Confirm database exists, if not create it
+if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -e "select * from ACCOUNT;" "$OPENSHIFT_APP_NAME" > /dev/null
+then
+	echo
+	echo "Schema not found --> Importing schema from .openshift/action_hooks/customer-schema.sql"
+	echo
+	/usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" "$OPENSHIFT_APP_NAME" < "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/customer-schema.sql"
+	echo
+	echo "done."
+else
+	echo "Database was found, skipping import."
+fi
